- name: Ensure configuration
  template:
    src: env.j2
    dest: "{{ bitwardenrs_directory }}/.env"
    owner: bitwardenrs
    group: bitwardenrs
    mode: u=rw,go=
  notify: Restart bitwardenrs

- name: Setup systemd service
  template:
    src: systemd.service.j2
    dest: /lib/systemd/system/bitwardenrs.service
  notify: Restart bitwardenrs
