- name: Ensure configuration
  template:
    src: "{{ _bitwardenrs_config_template }}"
    dest: "{{ bitwardenrs_directory }}/.env"
    owner: "{{ bitwardenrs_user }}"
    group: "{{ bitwardenrs_user_group }}"
    mode: u=rw,go=
  when: _bitwardenrs_config_template|length > 0
  notify: Restart bitwardenrs

- name: Setup systemd service
  template:
    src: systemd.service.j2
    dest: /lib/systemd/system/bitwardenrs.service
  notify: Restart bitwardenrs
