- name: Ensure configuration
  template:
    src: env.j2
    dest: "{{ bitwardenrs_directory }}/.env"
    owner: bitwardenrs
    group: bitwardenrs
    mode: u=rw,go=
  notify: Restart bitwardenrs

- name: Copy encryption rsa key
  copy:
    content: "{{ bitwardenrs_encryption_key }}"
    dest: "{{ bitwardenrs_datadir }}/rsa_key.pem"
    owner: bitwardenrs
    group: bitwardenrs
    mode: u=rw,go=
    force: "{{ bitwardenrs_force_encryption_key }}"
  register: __bitwardenrs_copy_encryption_rsa_key
  when: bitwardenrs_encryption_key|length > 0

- name: Remove old keys in DER format
  file:
    path: "{{ bitwardenrs_datadir }}/{{ item }}"
    state: absent
  loop:
    - rsa_key.der
    - rsa_key.pub.der
  when: __bitwardenrs_copy_encryption_rsa_key.changed

- name: Setup systemd service
  template:
    src: systemd.service.j2
    dest: /lib/systemd/system/bitwardenrs.service
  notify: Restart bitwardenrs
