- name: Ensure bitwardenrs directory
  file:
    path: "{{ bitwardenrs_directory }}"
    state: directory

- name: Install bitwarden_rs (and web-vault)
  include_tasks: install.yml

- name: Ensure configuration
  template:
    src: "{{ _bitwardenrs_config_template }}"
    dest: "{{ bitwardenrs_directory }}/.env"
    mode: u=rw,go=
  when: _bitwardenrs_config_template|length > 0

- name: Configure systemd
  include_tasks: systemd.yml
  when: bitwardenrs_systemd|bool