- include: preflight.yml
  tags:
    - bitwardenrs_install
    - bitwardenrs_configure
    - bitwardenrs_run

- include: user.yml
  become: yes
  when: not (bitwardenrs_user_external|bool or bitwardenrs_user == 'root')
  tags:
    - bitwardenrs_install

- include: install.yml
  become: yes
  tags:
    - bitwardenrs_install

- include: configure.yml
  become: yes
  tags:
    - bitwardenrs_configure

- name: Ensure bitwardenrs started and enabled
  become: yes
  systemd:
    name: bitwardenrs
    state: started
    enabled: yes
    daemon_reload: yes
  tags:
    - bitwardenrs_run