- name: Ensure bitwardenrs directory
  file:
    path: "{{ bitwardenrs_directory }}"
    state: directory

- name: Install bitwarden_rs and web-vault
  include_tasks: install.yml

- name: Configure bitwarden_rs
  include_tasks: configure.yml
  when: bitwardenrs_configure|bool

- name: Configure systemd
  include_tasks: systemd.yml
  when: bitwardenrs_systemd|bool