- name: Ensure bitwardenrs user/group
  include_tasks: user.yml
  when: not bitwardenrs_user_external|bool

- name: Install bitwarden_rs (and web-vault)
  include_tasks: install.yml

- name: Ensure configuration
  template:
    src: "{{ _bitwardenrs_config_template }}"
    dest: "{{ bitwardenrs_directory }}/.env"
    mode: u=rw,go=
  when: _bitwardenrs_config_template|length > 0
  notify: config changed

- name: Configure systemd
  include_tasks: systemd.yml
  when: bitwardenrs_systemd|bool

- name: Ensure permissions
  file:
    path: "{{ bitwardenrs_directory }}"
    state: directory
    owner: "{{ bitwardenrs_user }}"
    group: "{{ bitwardenrs_user_group }}"
    recurse: yes