- name: Create systemd service
  template:
    src: systemd.service.j2
    dest: /lib/systemd/system/bitwardenrs.service
  register: _bitwardenrs_systemd_service
  notify: systemd service changed

- name: Ensure bitwarden_rs started and enabled
  systemd:
    name: bitwardenrs
    state: started
    enabled: yes